version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/app
      - ./go.mod:/go.mod
      - ./go.sum:/go.sum
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOST: db
    tty: true
    networks:
      - echo_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
    networks:
      - echo_network

networks:
  echo_network:
    driver: bridge